#!/usr/bin/env sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

BUTTON=${button:-}
VALUE_COLOR=${color:-$(xrescat i3xrocks.value.color "#D8DEE9")}
LABEL_ICON=${label_icon:-$(xrescat i3xrocks.label.cpu "CPU")}
LABEL_COLOR=${label_color:-$(xrescat i3xrocks.label.color "#7B8394")}
VALUE_FONT=${font:-$(xrescat i3xrocks.value.font "JetBrains Mono Medium 13")}

load=$(cut -d ' ' -f1 /proc/loadavg)

# full text
printf "<span color=\"%s\">%s</span><span font_desc=\"%s\" color=\"%s\"> %.2f</span>\n" $LABEL_COLOR $LABEL_ICON "$VALUE_FONT" $VALUE_COLOR $load

# short text
echo "$load"

if [ "x${BUTTON}" == "x1" ]; then
    ACTION=$(xrescat i3xrocks.action.cpu-usage "/usr/bin/gnome-system-monitor --class=floating_window --show-resources-tab")
    /usr/bin/i3-msg -q exec "$ACTION"
fi
