alias c='clear'
alias ..='cd ..' 
alias ...='cd ../../../' 
alias ....='cd ../../../../' 
alias .....='cd ../../../../' 
alias .4='cd ../../../../' 
alias .5='cd ../../../../..'
alias mkdir='mkdir -pv'
alias ll='ls -l'
alias la='ls -a'
alias mux=tmuxinator
alias vim=nvim
alias vi=nvim
alias tmuxatt='tmux -2 attach'
